name: wasp-os simulator tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout files
      id:   checkout-files
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
          enable-cache: true

    - name: Install python modules
      id:   install-modules
      run:  uv sync --locked

    - name: Run the simulator tests
      id:   run-tests
      run:  |
          SDL_VIDEODRIVER=dummy \
          uv run make check
